# Generated by Django 4.2.7 on 2024-10-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_projects_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
